### ISSUE TITLE
[eslint] eslint-plugin-css-modules

### ISSUE THREAD

**Issue by godu** [CoorpAcademy/components#269]
- [ ] vérifier que les classes utilisées sont bien définies dans le fichier CSS
  https://github.com/css-modules
# YEP

``` CSS
.default {
  color: #F0F;
}
```

``` JavaScript
import {default} from './style.css';
```
# NOPE

``` CSS
.default {
  color: #F0F;
}
```

``` JavaScript
import {foo} from './style.css';
```
- [ ] publier sous `eslint-plugin-css-module`
